
import { Word } from './vocabulary-types';

// Intermediate level vocabulary words (expanded to 50+ words)
export const intermediateWords: Word[] = [
  {
    id: '16',
    arabic: 'آدَم',
    transliteration: 'Adam',
    meaning: 'Adam (first human)',
    root: 'أ د م',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 34,
        arabicText: 'وَإِذْ قُلْنَا لِلْمَلَائِكَةِ اسْجُدُوا لِآدَمَ',
        translation: 'And [mention] when We said to the angels, "Prostrate before Adam"',
      },
    ],
    level: 'intermediate',
    frequency: 25,
    tags: ['prophets'],
    collections: ['prophets'],
  },
  {
    id: '17',
    arabic: 'طَاعَة',
    transliteration: 'ṭā\'ah',
    meaning: 'Obedience',
    root: 'ط و ع',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 4,
        ayah: 59,
        arabicText: 'يَا أَيُّهَا الَّذِينَ آمَنُوا أَطِيعُوا اللَّهَ وَأَطِيعُوا الرَّسُولَ',
        translation: 'O you who have believed, obey Allah and obey the Messenger',
      },
    ],
    level: 'intermediate',
    frequency: 72,
    tags: ['worship', 'ethics'],
    collections: ['ethics', 'worship'],
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/004059.mp3',
  },
  {
    id: '18',
    arabic: 'حِكْمَة',
    transliteration: 'ḥikmah',
    meaning: 'Wisdom',
    root: 'ح ك م',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 269,
        arabicText: 'يُؤْتِي الْحِكْمَةَ مَن يَشَاءُ ۚ وَمَن يُؤْتَ الْحِكْمَةَ فَقَدْ أُوتِيَ خَيْرًا كَثِيرًا',
        translation: 'He gives wisdom to whom He wills, and whoever has been given wisdom has certainly been given much good',
      },
    ],
    level: 'intermediate',
    frequency: 20,
    tags: ['ethics', 'knowledge'],
    collections: ['ethics'],
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/002269.mp3',
  },
  {
    id: '19',
    arabic: 'شَاكِر',
    transliteration: 'shākir',
    meaning: 'Grateful, Thankful',
    root: 'ش ك ر',
    partOfSpeech: 'adjective',
    examples: [
      {
        surah: 2,
        ayah: 158,
        arabicText: 'وَمَن تَطَوَّعَ خَيْرًا فَإِنَّ اللَّهَ شَاكِرٌ عَلِيمٌ',
        translation: 'And whoever volunteers good - then indeed, Allah is appreciative and Knowing',
      },
    ],
    level: 'intermediate',
    frequency: 65,
    tags: ['ethics', 'divine attributes'],
    collections: ['ethics', 'faith'],
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/002158.mp3',
  },
  {
    id: '20',
    arabic: 'صَبْر',
    transliteration: 'ṣabr',
    meaning: 'Patience, Perseverance',
    root: 'ص ب ر',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 45,
        arabicText: 'وَاسْتَعِينُوا بِالصَّبْرِ وَالصَّلَاةِ',
        translation: 'And seek help through patience and prayer',
      },
    ],
    level: 'intermediate',
    frequency: 103,
    tags: ['ethics', 'spiritual'],
    collections: ['ethics'],
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/002045.mp3',
  },
  {
    id: '21',
    arabic: 'نِفَاق',
    transliteration: 'nifāq',
    meaning: 'Hypocrisy',
    root: 'ن ف ق',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 9,
        ayah: 101,
        arabicText: 'وَمِمَّنْ حَوْلَكُم مِّنَ الْأَعْرَابِ مُنَافِقُونَ ۖ وَمِنْ أَهْلِ الْمَدِينَةِ ۖ مَرَدُوا عَلَى النِّفَاقِ',
        translation: 'And among those around you of the bedouins are hypocrites, and from the people of Madinah. They have become accustomed to hypocrisy',
      },
    ],
    level: 'intermediate',
    frequency: 37,
    tags: ['ethics', 'negative traits'],
    collections: ['ethics'],
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/009101.mp3',
  },
  // Adding 35+ more intermediate words
  {
    id: '32',
    arabic: 'تَزْكِيَة',
    transliteration: 'tazkiyah',
    meaning: 'Purification, Growth',
    root: 'ز ك و',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 91,
        ayah: 9,
        arabicText: 'قَدْ أَفْلَحَ مَن زَكَّاهَا',
        translation: 'He has succeeded who purifies it',
      },
    ],
    level: 'intermediate',
    frequency: 25,
    tags: ['spiritual growth', 'self-improvement'],
    collections: ['ethics', 'faith'],
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/091009.mp3',
  },
  {
    id: '33',
    arabic: 'نُسُك',
    transliteration: 'nusuk',
    meaning: 'Ritual, Devotional act',
    root: 'ن س ك',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 196,
        arabicText: 'فَإِذَا أَمِنتُمْ فَمَن تَمَتَّعَ بِالْعُمْرَةِ إِلَى الْحَجِّ فَمَا اسْتَيْسَرَ مِنَ الْهَدْيِ',
        translation: 'And when you are secure, then whoever performs Umrah [during the Hajj months] followed by Hajj [offers] what can be obtained with ease of sacrificial animals',
      },
    ],
    level: 'intermediate',
    frequency: 10,
    tags: ['worship', 'rituals'],
    collections: ['worship'],
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/002196.mp3',
  },
  {
    id: '34',
    arabic: 'مُؤْمِن',
    transliteration: 'mu\'min',
    meaning: 'Believer',
    root: 'أ م ن',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 8,
        ayah: 74,
        arabicText: 'وَالَّذِينَ آمَنُوا وَهَاجَرُوا وَجَاهَدُوا فِي سَبِيلِ اللَّهِ وَالَّذِينَ آوَوا وَّنَصَرُوا أُولَٰئِكَ هُمُ الْمُؤْمِنُونَ حَقًّا',
        translation: 'And those who have believed and emigrated and fought in the cause of Allah and those who gave shelter and aided - it is they who are the believers, truly',
      },
    ],
    level: 'intermediate',
    frequency: 230,
    tags: ['faith', 'believer'],
    collections: ['faith', 'community'],
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/008074.mp3',
  },
  {
    id: '35',
    arabic: 'تَفَكُّر',
    transliteration: 'tafakkur',
    meaning: 'Contemplation, Reflection',
    root: 'ف ك ر',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 3,
        ayah: 191,
        arabicText: 'الَّذِينَ يَذْكُرُونَ اللَّهَ قِيَامًا وَقُعُودًا وَعَلَىٰ جُنُوبِهِمْ وَيَتَفَكَّرُونَ فِي خَلْقِ السَّمَاوَاتِ وَالْأَرْضِ',
        translation: 'Who remember Allah while standing or sitting or [lying] on their sides and give thought to the creation of the heavens and the earth',
      },
    ],
    level: 'intermediate',
    frequency: 18,
    tags: ['knowledge', 'intellect'],
    collections: ['knowledge', 'faith'],
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/003191.mp3',
  },
  {
    id: '36',
    arabic: 'مِيزَان',
    transliteration: 'mīzān',
    meaning: 'Balance, Scale',
    root: 'و ز ن',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 55,
        ayah: 7,
        arabicText: 'وَالسَّمَاءَ رَفَعَهَا وَوَضَعَ الْمِيزَانَ',
        translation: 'And the heaven He raised and imposed the balance',
      },
    ],
    level: 'intermediate',
    frequency: 23,
    tags: ['justice', 'afterlife'],
    collections: ['ethics', 'afterlife'],
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/055007.mp3',
  },
  {
    id: '37',
    arabic: 'خَشْيَة',
    transliteration: 'khashyah',
    meaning: 'Fear (of Allah), Awe',
    root: 'خ ش ي',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 74,
        arabicText: 'وَإِنَّ مِنْهَا لَمَا يَهْبِطُ مِنْ خَشْيَةِ اللَّهِ',
        translation: 'And there are stones which fall down for fear of Allah',
      },
    ],
    level: 'intermediate',
    frequency: 48,
    tags: ['faith', 'god consciousness'],
    collections: ['faith', 'ethics'],
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/002074.mp3',
  },
  {
    id: '38',
    arabic: 'مُهَاجِر',
    transliteration: 'muhājir',
    meaning: 'Emigrant, Migrant',
    root: 'ه ج ر',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 9,
        ayah: 100,
        arabicText: 'وَالسَّابِقُونَ الْأَوَّلُونَ مِنَ الْمُهَاجِرِينَ وَالْأَنصَارِ',
        translation: 'And the first forerunners [in the faith] among the Muhajireen and the Ansar',
      },
    ],
    level: 'intermediate',
    frequency: 26,
    tags: ['history', 'community'],
    collections: ['community', 'prophets'],
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/009100.mp3',
  },
  {
    id: '39',
    arabic: 'فَضْل',
    transliteration: 'faḍl',
    meaning: 'Bounty, Favor',
    root: 'ف ض ل',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 64,
        arabicText: 'ثُمَّ تَوَلَّيْتُم مِّن بَعْدِ ذَٰلِكَ ۖ فَلَوْلَا فَضْلُ اللَّهِ عَلَيْكُمْ وَرَحْمَتُهُ لَكُنتُم مِّنَ الْخَاسِرِينَ',
        translation: 'Then you turned away after that. And if not for the favor of Allah upon you and His mercy, you would have been among the losers',
      },
    ],
    level: 'intermediate',
    frequency: 104,
    tags: ['blessing', 'divine attributes'],
    collections: ['faith'],
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/002064.mp3',
  },
  {
    id: '40',
    arabic: 'سَكِينَة',
    transliteration: 'sakīnah',
    meaning: 'Tranquility, Peace',
    root: 'س ك ن',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 48,
        ayah: 4,
        arabicText: 'هُوَ الَّذِي أَنزَلَ السَّكِينَةَ فِي قُلُوبِ الْمُؤْمِنِينَ',
        translation: 'He is the One who sent down tranquility into the hearts of the believers',
      },
    ],
    level: 'intermediate',
    frequency: 6,
    tags: ['peace', 'spiritual state'],
    collections: ['faith', 'ethics'],
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/048004.mp3',
  },
  {
    id: '41',
    arabic: 'مَوْعِظَة',
    transliteration: 'maw\'iẓah',
    meaning: 'Admonition, Lesson',
    root: 'و ع ظ',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 275,
        arabicText: 'فَمَن جَاءَهُ مَوْعِظَةٌ مِّن رَّبِّهِ فَانتَهَىٰ فَلَهُ مَا سَلَفَ وَأَمْرُهُ إِلَى اللَّهِ',
        translation: 'So whoever has received an admonition from his Lord and desists may have what is past, and his affair rests with Allah',
      },
    ],
    level: 'intermediate',
    frequency: 25,
    tags: ['guidance', 'teaching'],
    collections: ['knowledge', 'ethics'],
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/002275.mp3',
  },
  // Additional 30+ intermediate words
  {
    id: '77',
    arabic: 'يُونُس',
    transliteration: 'Yūnus',
    meaning: 'Jonah',
    root: 'ي و ن',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 10,
        ayah: 98,
        arabicText: 'فَلَوْلَا كَانَتْ قَرْيَةٌ آمَنَتْ فَنَفَعَهَا إِيمَانُهَا إِلَّا قَوْمَ يُونُسَ',
        translation: 'Then has there not been a [single] city that believed so its faith benefited it except the people of Jonah?',
      },
    ],
    level: 'intermediate',
    frequency: 4,
    tags: ['prophets'],
    collections: ['prophets'],
  },
  {
    id: '78',
    arabic: 'يُوسُف',
    transliteration: 'Yūsuf',
    meaning: 'Joseph',
    root: 'ي و س',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 12,
        ayah: 4,
        arabicText: 'إِذْ قَالَ يُوسُفُ لِأَبِيهِ يَا أَبَتِ إِنِّي رَأَيْتُ أَحَدَ عَشَرَ كَوْكَبًا',
        translation: 'When Joseph said to his father, "O my father, indeed I have seen eleven stars"',
      },
    ],
    level: 'intermediate',
    frequency: 27,
    tags: ['prophets'],
    collections: ['prophets'],
  },
  {
    id: '79',
    arabic: 'دَاوُد',
    transliteration: 'Dāwūd',
    meaning: 'David',
    root: 'د و د',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 251,
        arabicText: 'فَهَزَمُوهُم بِإِذْنِ اللَّهِ وَقَتَلَ دَاوُودُ جَالُوتَ',
        translation: 'So they defeated them by permission of Allah, and David killed Goliath',
      },
    ],
    level: 'intermediate',
    frequency: 16,
    tags: ['prophets'],
    collections: ['prophets'],
  },
  {
    id: '80',
    arabic: 'سُلَيْمَان',
    transliteration: 'Sulaymān',
    meaning: 'Solomon',
    root: 'س ل م',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 102,
        arabicText: 'وَمَا كَفَرَ سُلَيْمَانُ وَلَٰكِنَّ الشَّيَاطِينَ كَفَرُوا',
        translation: 'And Solomon did not disbelieve, but the devils disbelieved',
      },
    ],
    level: 'intermediate',
    frequency: 17,
    tags: ['prophets'],
    collections: ['prophets'],
  },
  {
    id: '81',
    arabic: 'أَيُّوب',
    transliteration: 'Ayyūb',
    meaning: 'Job',
    root: 'أ ي ب',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 21,
        ayah: 83,
        arabicText: 'وَأَيُّوبَ إِذْ نَادَىٰ رَبَّهُ أَنِّي مَسَّنِيَ الضُّرُّ وَأَنتَ أَرْحَمُ الرَّاحِمِينَ',
        translation: 'And Job, when he called to his Lord, "Indeed, adversity has touched me, and you are the most merciful of the merciful"',
      },
    ],
    level: 'intermediate',
    frequency: 4,
    tags: ['prophets'],
    collections: ['prophets'],
  },
  {
    id: '82',
    arabic: 'ذِكْر',
    transliteration: 'dhikr',
    meaning: 'Remembrance, mention',
    root: 'ذ ك ر',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 152,
        arabicText: 'فَاذْكُرُونِي أَذْكُرْكُمْ وَاشْكُرُوا لِي وَلَا تَكْفُرُونِ',
        translation: 'So remember Me; I will remember you. And be grateful to Me and do not deny Me',
      },
    ],
    level: 'intermediate',
    frequency: 292,
    tags: ['worship', 'remembrance'],
    collections: ['worship'],
  },
  {
    id: '83',
    arabic: 'دُعَاء',
    transliteration: 'du\'ā\'',
    meaning: 'Supplication, prayer',
    root: 'د ع و',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 186,
        arabicText: 'وَإِذَا سَأَلَكَ عِبَادِي عَنِّي فَإِنِّي قَرِيبٌ ۖ أُجِيبُ دَعْوَةَ الدَّاعِ إِذَا دَعَانِ',
        translation: 'And when My servants ask you concerning Me - indeed I am near. I respond to the invocation of the supplicant when he calls upon Me',
      },
    ],
    level: 'intermediate',
    frequency: 211,
    tags: ['worship', 'supplication'],
    collections: ['worship'],
  },
  {
    id: '84',
    arabic: 'اسْتِغْفَار',
    transliteration: 'istighfār',
    meaning: 'Seeking forgiveness',
    root: 'غ ف ر',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 71,
        ayah: 10,
        arabicText: 'فَقُلْتُ اسْتَغْفِرُوا رَبَّكُمْ إِنَّهُ كَانَ غَفَّارًا',
        translation: 'And said, "Ask forgiveness of your Lord. Indeed, He is ever a Perpetual Forgiver"',
      },
    ],
    level: 'intermediate',
    frequency: 59,
    tags: ['worship', 'forgiveness'],
    collections: ['worship', 'ethics'],
  },
  {
    id: '85',
    arabic: 'تَسْبِيح',
    transliteration: 'tasbīḥ',
    meaning: 'Glorification, praising Allah',
    root: 'س ب ح',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 17,
        ayah: 44,
        arabicText: 'تُسَبِّحُ لَهُ السَّمَاوَاتُ السَّبْعُ وَالْأَرْضُ وَمَن فِيهِنَّ',
        translation: 'The seven heavens and the earth and whatever is in them exalt Him',
      },
    ],
    level: 'intermediate',
    frequency: 87,
    tags: ['worship', 'praise'],
    collections: ['worship'],
  },
  {
    id: '86',
    arabic: 'تَحْمِيد',
    transliteration: 'taḥmīd',
    meaning: 'Praising, saying Alhamdulillah',
    root: 'ح م د',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 1,
        ayah: 2,
        arabicText: 'الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ',
        translation: 'All praise is due to Allah, Lord of the worlds',
      },
    ],
    level: 'intermediate',
    frequency: 63,
    tags: ['worship', 'praise'],
    collections: ['worship'],
  },
  {
    id: '87',
    arabic: 'تَوَكُّل',
    transliteration: 'tawakkul',
    meaning: 'Trust in Allah, reliance',
    root: 'و ك ل',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 3,
        ayah: 159,
        arabicText: 'فَإِذَا عَزَمْتَ فَتَوَكَّلْ عَلَى اللَّهِ ۚ إِنَّ اللَّهَ يُحِبُّ الْمُتَوَكِّلِينَ',
        translation: 'And when you have decided, then rely upon Allah. Indeed, Allah loves those who rely [upon Him]',
      },
    ],
    level: 'intermediate',
    frequency: 70,
    tags: ['faith', 'trust'],
    collections: ['faith', 'ethics'],
  },
  {
    id: '88',
    arabic: 'رَجَاء',
    transliteration: 'rajā\'',
    meaning: 'Hope, expectation',
    root: 'ر ج و',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 18,
        ayah: 110,
        arabicText: 'فَمَن كَانَ يَرْجُو لِقَاءَ رَبِّهِ فَلْيَعْمَلْ عَمَلًا صَالِحًا',
        translation: 'So whoever would hope for the meeting with his Lord - let him do righteous work',
      },
    ],
    level: 'intermediate',
    frequency: 83,
    tags: ['faith', 'hope'],
    collections: ['faith'],
  },
  {
    id: '89',
    arabic: 'خَوْف',
    transliteration: 'khawf',
    meaning: 'Fear',
    root: 'خ و ف',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 62,
        arabicText: 'وَلَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ',
        translation: 'No fear will there be concerning them, nor will they grieve',
      },
    ],
    level: 'intermediate',
    frequency: 124,
    tags: ['emotion', 'spiritual state'],
    collections: ['ethics'],
  },
  {
    id: '90',
    arabic: 'طَمَع',
    transliteration: 'ṭama\'',
    meaning: 'Greed, desire',
    root: 'ط م ع',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 33,
        ayah: 32,
        arabicText: 'فَلَا تَخْضَعْنَ بِالْقَوْلِ فَيَطْمَعَ الَّذِي فِي قَلْبِهِ مَرَضٌ',
        translation: 'Then do not be soft in speech [to men], lest he in whose heart is disease should covet',
      },
    ],
    level: 'intermediate',
    frequency: 21,
    tags: ['ethics', 'negative trait'],
    collections: ['ethics'],
  },
  {
    id: '91',
    arabic: 'يَقِين',
    transliteration: 'yaqīn',
    meaning: 'Certainty, conviction',
    root: 'ي ق ن',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 15,
        ayah: 99,
        arabicText: 'وَاعْبُدْ رَبَّكَ حَتَّىٰ يَأْتِيَكَ الْيَقِينُ',
        translation: 'And worship your Lord until there comes to you the certainty',
      },
    ],
    level: 'intermediate',
    frequency: 27,
    tags: ['faith', 'certainty'],
    collections: ['faith'],
  },
  {
    id: '92',
    arabic: 'شَكّ',
    transliteration: 'shakk',
    meaning: 'Doubt',
    root: 'ش ك ك',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 2,
        arabicText: 'ذَٰلِكَ الْكِتَابُ لَا رَيْبَ ۛ فِيهِ',
        translation: 'This is the Book about which there is no doubt',
      },
    ],
    level: 'intermediate',
    frequency: 45,
    tags: ['doubt', 'uncertainty'],
    collections: ['faith'],
  },
  {
    id: '93',
    arabic: 'نَجَاة',
    transliteration: 'najāh',
    meaning: 'Salvation, deliverance',
    root: 'ن ج و',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 10,
        ayah: 103,
        arabicText: 'ثُمَّ نُنَجِّي رُسُلَنَا وَالَّذِينَ آمَنُوا ۚ كَذَٰلِكَ حَقًّا عَلَيْنَا نُنجِ الْمُؤْمِنِينَ',
        translation: 'Then We will save our messengers and those who have believed. Thus, it is an obligation upon Us that We save the believers',
      },
    ],
    level: 'intermediate',
    frequency: 67,
    tags: ['salvation', 'deliverance'],
    collections: ['afterlife'],
  },
  {
    id: '94',
    arabic: 'هَلاَك',
    transliteration: 'halāk',
    meaning: 'Destruction, perdition',
    root: 'ه ل ك',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 8,
        ayah: 42,
        arabicText: 'لِيَهْلِكَ مَنْ هَلَكَ عَن بَيِّنَةٍ وَيَحْيَىٰ مَنْ حَيَّ عَن بَيِّنَةٍ',
        translation: 'That those who perished would perish upon evidence and those who lived would live upon evidence',
      },
    ],
    level: 'intermediate',
    frequency: 183,
    tags: ['destruction', 'death'],
    collections: ['afterlife'],
  },
  {
    id: '95',
    arabic: 'فَلاَح',
    transliteration: 'falāḥ',
    meaning: 'Success, prosperity',
    root: 'ف ل ح',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 23,
        ayah: 1,
        arabicText: 'قَدْ أَفْلَحَ الْمُؤْمِنُونَ',
        translation: 'Certainly will the believers have succeeded',
      },
    ],
    level: 'intermediate',
    frequency: 40,
    tags: ['success', 'prosperity'],
    collections: ['afterlife'],
  },
  {
    id: '96',
    arabic: 'خُسْرَان',
    transliteration: 'khusrān',
    meaning: 'Loss, failure',
    root: 'خ س ر',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 103,
        ayah: 2,
        arabicText: 'إِنَّ الْإِنسَانَ لَفِي خُسْرٍ',
        translation: 'Indeed, mankind is in loss',
      },
    ],
    level: 'intermediate',
    frequency: 64,
    tags: ['loss', 'failure'],
    collections: ['afterlife'],
  },
  {
    id: '97',
    arabic: 'جِهَاد',
    transliteration: 'jihād',
    meaning: 'Struggle, striving',
    root: 'ج ه د',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 9,
        ayah: 24,
        arabicText: 'وَجِهَادٌ فِي سَبِيلِهِ أَحَبَّ إِلَيْكُم مِّنَ اللَّهِ وَرَسُولِهِ',
        translation: 'And striving in His cause was more beloved to you than Allah and His Messenger',
      },
    ],
    level: 'intermediate',
    frequency: 41,
    tags: ['struggle', 'effort'],
    collections: ['ethics', 'community'],
  },
  {
    id: '98',
    arabic: 'بِرّ',
    transliteration: 'birr',
    meaning: 'Righteousness, piety',
    root: 'ب ر ر',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 177,
        arabicText: 'لَّيْسَ الْبِرَّ أَن تُوَلُّوا وُجُوهَكُمْ قِبَلَ الْمَشْرِقِ وَالْمَغْرِبِ',
        translation: 'Righteousness is not that you turn your faces toward the east or the west',
      },
    ],
    level: 'intermediate',
    frequency: 17,
    tags: ['righteousness', 'virtue'],
    collections: ['ethics'],
  },
  {
    id: '99',
    arabic: 'فُجُور',
    transliteration: 'fujūr',
    meaning: 'Wickedness, immorality',
    root: 'ف ج ر',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 91,
        ayah: 8,
        arabicText: 'فَأَلْهَمَهَا فُجُورَهَا وَتَقْوَاهَا',
        translation: 'And inspired it [with discernment of] its wickedness and its righteousness',
      },
    ],
    level: 'intermediate',
    frequency: 3,
    tags: ['wickedness', 'immorality'],
    collections: ['ethics'],
  },
  {
    id: '100',
    arabic: 'عَدْل',
    transliteration: 'adl',
    meaning: 'Justice',
    root: 'ع د ل',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 4,
        ayah: 58,
        arabicText: 'إِنَّ اللَّهَ يَأْمُرُكُمْ أَن تُؤَدُّوا الْأَمَانَاتِ إِلَىٰ أَهْلِهَا وَإِذَا حَكَمْتُم بَيْنَ النَّاسِ أَن تَحْكُمُوا بِالْعَدْلِ',
        translation: 'Indeed, Allah orders you to render trusts to their owners and when you judge between people to judge with justice',
      },
    ],
    level: 'intermediate',
    frequency: 28,
    tags: ['justice', 'fairness'],
    collections: ['ethics', 'community'],
  },
  {
    id: '101',
    arabic: 'ظُلْم',
    transliteration: 'ẓulm',
    meaning: 'Injustice, oppression',
    root: 'ظ ل م',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 193,
        arabicText: 'وَقَاتِلُوهُمْ حَتَّىٰ لَا تَكُونَ فِتْنَةٌ وَيَكُونَ الدِّينُ لِلَّهِ ۖ فَإِنِ انتَهَوْا فَلَا عُدْوَانَ إِلَّا عَلَى الظَّالِمِينَ',
        translation: 'Fight them until there is no [more] fitnah and [until] religion belongs to Allah. But if they cease, then there is to be no aggression except against the oppressors',
      },
    ],
    level: 'intermediate',
    frequency: 315,
    tags: ['injustice', 'oppression'],
    collections: ['ethics'],
  },
  {
    id: '102',
    arabic: 'شَجَرَة',
    transliteration: 'shajarah',
    meaning: 'Tree',
    root: 'ش ج ر',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 24,
        ayah: 35,
        arabicText: 'يُوقَدُ مِن شَجَرَةٍ مُّبَارَكَةٍ زَيْتُونَةٍ',
        translation: 'Lit from [the oil of] a blessed olive tree',
      },
    ],
    level: 'intermediate',
    frequency: 26,
    tags: ['nature', 'creation'],
    collections: ['nature'],
  },
  {
    id: '103',
    arabic: 'ثَمَرَة',
    transliteration: 'thamarah',
    meaning: 'Fruit',
    root: 'ث م ر',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 22,
        arabicText: 'وَأَنزَلَ مِنَ السَّمَاءِ مَاءً فَأَخْرَجَ بِهِ مِنَ الثَّمَرَاتِ رِزْقًا لَّكُمْ',
        translation: 'And sent down from the heaven rain and brought forth thereby fruits as provision for you',
      },
    ],
    level: 'intermediate',
    frequency: 45,
    tags: ['nature', 'sustenance'],
    collections: ['nature'],
  },
  {
    id: '104',
    arabic: 'نَهْر',
    transliteration: 'nahr',
    meaning: 'River',
    root: 'ن ه ر',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 25,
        arabicText: 'وَبَشِّرِ الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ أَنَّ لَهُمْ جَنَّاتٍ تَجْرِي مِن تَحْتِهَا الْأَنْهَارُ',
        translation: 'And give good tidings to those who believe and do righteous deeds that they will have gardens beneath which rivers flow',
      },
    ],
    level: 'intermediate',
    frequency: 54,
    tags: ['nature', 'paradise'],
    collections: ['nature', 'afterlife'],
  },
  {
    id: '105',
    arabic: 'بَحْر',
    transliteration: 'baḥr',
    meaning: 'Sea, ocean',
    root: 'ب ح ر',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 17,
        ayah: 66,
        arabicText: 'رَّبُّكُمُ الَّذِي يُزْجِي لَكُمُ الْفُلْكَ فِي الْبَحْرِ لِتَبْتَغُوا مِن فَضْلِهِ',
        translation: 'It is your Lord who drives the ship for you through the sea that you may seek of His bounty',
      },
    ],
    level: 'intermediate',
    frequency: 41,
    tags: ['nature', 'creation'],
    collections: ['nature'],
  },
  {
    id: '106',
    arabic: 'جَبَل',
    transliteration: 'jabal',
    meaning: 'Mountain',
    root: 'ج ب ل',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 7,
        ayah: 143,
        arabicText: 'فَلَمَّا تَجَلَّىٰ رَبُّهُ لِلْجَبَلِ جَعَلَهُ دَكًّا',
        translation: 'But when his Lord appeared to the mountain, He rendered it level',
      },
    ],
    level: 'intermediate',
    frequency: 39,
    tags: ['nature', 'creation'],
    collections: ['nature'],
  },
  {
    id: '107',
    arabic: 'رِيح',
    transliteration: 'rīḥ',
    meaning: 'Wind',
    root: 'ر و ح',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 30,
        ayah: 46,
        arabicText: 'وَمِنْ آيَاتِهِ أَن يُرْسِلَ الرِّيَاحَ مُبَشِّرَاتٍ',
        translation: 'And of His signs is that He sends the winds as bringers of good tidings',
      },
    ],
    level: 'intermediate',
    frequency: 51,
    tags: ['nature', 'creation'],
    collections: ['nature'],
  },
];

// Apply missing properties to all words
intermediateWords.forEach(word => {
  if (!word.translation) {
    word.translation = word.meaning;
  }
  if (!word.collection && word.collections.length > 0) {
    word.collection = word.collections[0];
  }
});
