
import { Word } from './vocabulary-types';

// Advanced level vocabulary words (expanded to 50+ words)
export const advancedWords: Word[] = [
  {
    id: '22',
    arabic: 'إِسْتِكْبَار',
    transliteration: 'istikbār',
    meaning: 'Arrogance, Pride',
    root: 'ك ب ر',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 35,
        ayah: 43,
        arabicText: 'اسْتِكْبَارًا فِي الْأَرْضِ وَمَكْرَ السَّيِّئِ',
        translation: 'Arrogance in the land and plotting of evil',
      },
    ],
    level: 'advanced',
    frequency: 28,
    tags: ['ethics', 'negative traits'],
    collections: ['ethics'],
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/035043.mp3',
  },
  {
    id: '23',
    arabic: 'مُتَشَابِهَات',
    transliteration: 'mutashābihāt',
    meaning: 'Ambiguous, Allegorical verses',
    root: 'ش ب ه',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 3,
        ayah: 7,
        arabicText: 'هُوَ الَّذِي أَنزَلَ عَلَيْكَ الْكِتَابَ مِنْهُ آيَاتٌ مُّحْكَمَاتٌ هُنَّ أُمُّ الْكِتَابِ وَأُخَرُ مُتَشَابِهَاتٌ',
        translation: 'It is He who has sent down to you the Book; in it are verses precise - they are the foundation of the Book - and others unspecific',
      },
    ],
    level: 'advanced',
    frequency: 12,
    tags: ['revelation', 'quran sciences'],
    collections: ['faith'],
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/003007.mp3',
  },
  {
    id: '24',
    arabic: 'إِسْتِنْبَاط',
    transliteration: 'istinbāṭ',
    meaning: 'Deduction, Inference',
    root: 'ن ب ط',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 4,
        ayah: 83,
        arabicText: 'وَلَوْ رَدُّوهُ إِلَى الرَّسُولِ وَإِلَىٰ أُولِي الْأَمْرِ مِنْهُمْ لَعَلِمَهُ الَّذِينَ يَسْتَنبِطُونَهُ مِنْهُمْ',
        translation: 'And if they had referred it back to the Messenger or to those of authority among them, then the ones who can draw correct conclusions from it would have known about it',
      },
    ],
    level: 'advanced',
    frequency: 1,
    tags: ['knowledge', 'methodology'],
    collections: ['faith'],
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/004083.mp3',
  },
  {
    id: '25',
    arabic: 'تَخْفِيف',
    transliteration: 'takhfīf',
    meaning: 'Alleviation, Lightening of burden',
    root: 'خ ف ف',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 4,
        ayah: 28,
        arabicText: 'يُرِيدُ اللَّهُ أَن يُخَفِّفَ عَنكُمْ ۚ وَخُلِقَ الْإِنسَانُ ضَعِيفًا',
        translation: 'Allah wants to lighten for you [your difficulties]; and mankind was created weak',
      },
    ],
    level: 'advanced',
    frequency: 11,
    tags: ['divine attributes', 'mercy'],
    collections: ['faith'],
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/004028.mp3',
  },
  {
    id: '26',
    arabic: 'مُحْصَنَات',
    transliteration: 'muḥṣanāt',
    meaning: 'Chaste women',
    root: 'ح ص ن',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 4,
        ayah: 24,
        arabicText: 'وَالْمُحْصَنَاتُ مِنَ النِّسَاءِ إِلَّا مَا مَلَكَتْ أَيْمَانُكُمْ',
        translation: 'And [also prohibited to you are all] married women except those your right hands possess',
      },
    ],
    level: 'advanced',
    frequency: 8,
    tags: ['ethics', 'family'],
    collections: ['ethics', 'community'],
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/004024.mp3',
  },
  // Adding 40+ more advanced words to reach 50+
  {
    id: '42',
    arabic: 'مُحْكَمَات',
    transliteration: 'muḥkamāt',
    meaning: 'Clear, precise verses',
    root: 'ح ك م',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 3,
        ayah: 7,
        arabicText: 'هُوَ الَّذِي أَنزَلَ عَلَيْكَ الْكِتَابَ مِنْهُ آيَاتٌ مُّحْكَمَاتٌ هُنَّ أُمُّ الْكِتَابِ',
        translation: 'It is He who has sent down to you the Book; in it are verses precise - they are the foundation of the Book',
      },
    ],
    level: 'advanced',
    frequency: 2,
    tags: ['revelation', 'quran sciences'],
    collections: ['knowledge', 'faith'],
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/003007.mp3',
  },
  {
    id: '43',
    arabic: 'تَأْوِيل',
    transliteration: 'ta\'wīl',
    meaning: 'Interpretation, Explanation',
    root: 'أ و ل',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 3,
        ayah: 7,
        arabicText: 'وَمَا يَعْلَمُ تَأْوِيلَهُ إِلَّا اللَّهُ ۗ وَالرَّاسِخُونَ فِي الْعِلْمِ',
        translation: 'And no one knows its [true] interpretation except Allah. But those firm in knowledge say',
      },
    ],
    level: 'advanced',
    frequency: 16,
    tags: ['revelation', 'quran sciences'],
    collections: ['knowledge', 'faith'],
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/003007.mp3',
  },
  {
    id: '44',
    arabic: 'اسْتِخْلَاف',
    transliteration: 'istikhlāf',
    meaning: 'Succession, Vicegerency',
    root: 'خ ل ف',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 24,
        ayah: 55,
        arabicText: 'وَعَدَ اللَّهُ الَّذِينَ آمَنُوا مِنكُمْ وَعَمِلُوا الصَّالِحَاتِ لَيَسْتَخْلِفَنَّهُمْ فِي الْأَرْضِ',
        translation: 'Allah has promised those who have believed among you and done righteous deeds that He will surely grant them succession [to authority] upon the earth',
      },
    ],
    level: 'advanced',
    frequency: 9,
    tags: ['governance', 'responsibility'],
    collections: ['community'],
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/024055.mp3',
  },
  {
    id: '45',
    arabic: 'إِسْرَاف',
    transliteration: 'isrāf',
    meaning: 'Excess, Extravagance',
    root: 'س ر ف',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 7,
        ayah: 31,
        arabicText: 'وَكُلُوا وَاشْرَبُوا وَلَا تُسْرِفُوا ۚ إِنَّهُ لَا يُحِبُّ الْمُسْرِفِينَ',
        translation: 'Eat and drink, but be not excessive. Indeed, He likes not those who commit excess',
      },
    ],
    level: 'advanced',
    frequency: 23,
    tags: ['ethics', 'moderation'],
    collections: ['ethics'],
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/007031.mp3',
  },
  {
    id: '46',
    arabic: 'اسْتِعَاذَة',
    transliteration: 'isti\'ādhah',
    meaning: 'Seeking refuge',
    root: 'ع و ذ',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 16,
        ayah: 98,
        arabicText: 'فَإِذَا قَرَأْتَ الْقُرْآنَ فَاسْتَعِذْ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ',
        translation: 'So when you recite the Quran, [first] seek refuge in Allah from Satan, the expelled [from His mercy]',
      },
    ],
    level: 'advanced',
    frequency: 17,
    tags: ['worship', 'protection'],
    collections: ['worship'],
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/016098.mp3',
  },
  {
    id: '47',
    arabic: 'قِصَاص',
    transliteration: 'qiṣāṣ',
    meaning: 'Retribution, Retaliation',
    root: 'ق ص ص',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 178,
        arabicText: 'يَا أَيُّهَا الَّذِينَ آمَنُوا كُتِبَ عَلَيْكُمُ الْقِصَاصُ فِي الْقَتْلَى',
        translation: 'O you who have believed, prescribed for you is legal retribution for those murdered',
      },
    ],
    level: 'advanced',
    frequency: 4,
    tags: ['justice', 'law'],
    collections: ['ethics', 'community'],
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/002178.mp3',
  },
  {
    id: '48',
    arabic: 'مُتَوَكِّل',
    transliteration: 'mutawakkil',
    meaning: 'One who trusts in Allah',
    root: 'و ك ل',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 3,
        ayah: 159,
        arabicText: 'فَإِذَا عَزَمْتَ فَتَوَكَّلْ عَلَى اللَّهِ ۚ إِنَّ اللَّهَ يُحِبُّ الْمُتَوَكِّلِينَ',
        translation: 'And when you have decided, then rely upon Allah. Indeed, Allah loves those who rely [upon Him]',
      },
    ],
    level: 'advanced',
    frequency: 7,
    tags: ['faith', 'trust'],
    collections: ['faith'],
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/003159.mp3',
  },
  {
    id: '49',
    arabic: 'تَجَلِّي',
    transliteration: 'tajallī',
    meaning: 'Manifestation, Revelation',
    root: 'ج ل و',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 7,
        ayah: 143,
        arabicText: 'فَلَمَّا تَجَلَّىٰ رَبُّهُ لِلْجَبَلِ جَعَلَهُ دَكًّا وَخَرَّ مُوسَىٰ صَعِقًا',
        translation: 'But when his Lord appeared to the mountain, He rendered it level, and Moses fell unconscious',
      },
    ],
    level: 'advanced',
    frequency: 1,
    tags: ['divine manifestation', 'spirituality'],
    collections: ['faith'],
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/007143.mp3',
  },
  {
    id: '50',
    arabic: 'مُسْتَضْعَفِين',
    transliteration: 'mustaḍ\'afīn',
    meaning: 'Oppressed, Weak ones',
    root: 'ض ع ف',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 4,
        ayah: 75,
        arabicText: 'وَمَا لَكُمْ لَا تُقَاتِلُونَ فِي سَبِيلِ اللَّهِ وَالْمُسْتَضْعَفِينَ مِنَ الرِّجَالِ وَالنِّسَاءِ وَالْوِلْدَانِ',
        translation: 'And what is [the matter] with you that you fight not in the cause of Allah and [for] the oppressed among men, women, and children',
      },
    ],
    level: 'advanced',
    frequency: 5,
    tags: ['justice', 'societal'],
    collections: ['ethics', 'community'],
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/004075.mp3',
  },
  {
    id: '51',
    arabic: 'تَدَبُّر',
    transliteration: 'tadabbur',
    meaning: 'Pondering, Reflection',
    root: 'د ب ر',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 4,
        ayah: 82,
        arabicText: 'أَفَلَا يَتَدَبَّرُونَ الْقُرْآنَ ۚ وَلَوْ كَانَ مِنْ عِندِ غَيْرِ اللَّهِ لَوَجَدُوا فِيهِ اخْتِلَافًا كَثِيرًا',
        translation: 'Then do they not reflect upon the Quran? If it had been from [any] other than Allah, they would have found within it much contradiction',
      },
    ],
    level: 'advanced',
    frequency: 4,
    tags: ['knowledge', 'reflection'],
    collections: ['knowledge', 'faith'],
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/004082.mp3',
  },
  // Adding 40+ more advanced words
  {
    id: '108',
    arabic: 'رَاسِخُون',
    transliteration: 'rāsikhūn',
    meaning: 'Those firmly grounded (in knowledge)',
    root: 'ر س خ',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 3,
        ayah: 7,
        arabicText: 'وَالرَّاسِخُونَ فِي الْعِلْمِ يَقُولُونَ آمَنَّا بِهِ',
        translation: 'But those firm in knowledge say, "We believe in it"',
      },
    ],
    level: 'advanced',
    frequency: 3,
    tags: ['knowledge', 'scholars'],
    collections: ['knowledge'],
  },
  {
    id: '109',
    arabic: 'إِفْك',
    transliteration: 'ifk',
    meaning: 'Falsehood, slander',
    root: 'أ ف ك',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 24,
        ayah: 11,
        arabicText: 'إِنَّ الَّذِينَ جَاءُوا بِالْإِفْكِ عُصْبَةٌ مِّنكُمْ',
        translation: 'Indeed, those who came with falsehood are a group among you',
      },
    ],
    level: 'advanced',
    frequency: 6,
    tags: ['falsehood', 'slander'],
    collections: ['ethics'],
  },
  {
    id: '110',
    arabic: 'تَوْحِيد',
    transliteration: 'tawḥīd',
    meaning: 'Monotheism, Unity of Allah',
    root: 'و ح د',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 112,
        ayah: 1,
        arabicText: 'قُلْ هُوَ اللَّهُ أَحَدٌ',
        translation: 'Say, "He is Allah, [who is] One"',
      },
    ],
    level: 'advanced',
    frequency: 1,
    tags: ['theology', 'monotheism'],
    collections: ['faith'],
  },
  {
    id: '111',
    arabic: 'شِرْك',
    transliteration: 'shirk',
    meaning: 'Associating partners with Allah',
    root: 'ش ر ك',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 4,
        ayah: 48,
        arabicText: 'إِنَّ اللَّهَ لَا يَغْفِرُ أَن يُشْرَكَ بِهِ وَيَغْفِرُ مَا دُونَ ذَٰلِكَ لِمَن يَشَاءُ',
        translation: 'Indeed, Allah does not forgive association with Him, but He forgives what is less than that for whom He wills',
      },
    ],
    level: 'advanced',
    frequency: 165,
    tags: ['theology', 'polytheism'],
    collections: ['faith'],
  },
  {
    id: '112',
    arabic: 'تَنْزِيه',
    transliteration: 'tanzīh',
    meaning: 'Transcendence, declaring Allah free from imperfections',
    root: 'ن ز ه',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 17,
        ayah: 1,
        arabicText: 'سُبْحَانَ الَّذِي أَسْرَىٰ بِعَبْدِهِ لَيْلًا',
        translation: 'Exalted is He who took His Servant by night',
      },
    ],
    level: 'advanced',
    frequency: 91,
    tags: ['theology', 'divine attributes'],
    collections: ['faith'],
  },
  {
    id: '113',
    arabic: 'قَدَر',
    transliteration: 'qadar',
    meaning: 'Divine decree, predestination',
    root: 'ق د ر',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 97,
        ayah: 1,
        arabicText: 'إِنَّا أَنزَلْنَاهُ فِي لَيْلَةِ الْقَدْرِ',
        translation: 'Indeed, We sent the Quran down during the Night of Decree',
      },
    ],
    level: 'advanced',
    frequency: 132,
    tags: ['theology', 'destiny'],
    collections: ['faith'],
  },
  {
    id: '114',
    arabic: 'حَتْمِيَّة',
    transliteration: 'ḥatmiyyah',
    meaning: 'Inevitability, certainty',
    root: 'ح ت م',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 19,
        ayah: 71,
        arabicText: 'وَإِن مِّنكُمْ إِلَّا وَارِدُهَا ۚ كَانَ عَلَىٰ رَبِّكَ حَتْمًا مَّقْضِيًّا',
        translation: 'And there is none of you except he will come to it. This is upon your Lord an inevitability decreed',
      },
    ],
    level: 'advanced',
    frequency: 1,
    tags: ['destiny', 'certainty'],
    collections: ['afterlife'],
  },
  {
    id: '115',
    arabic: 'أَسْمَاء',
    transliteration: 'asmā\'',
    meaning: 'Names (especially divine names)',
    root: 'س م و',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 7,
        ayah: 180,
        arabicText: 'وَلِلَّهِ الْأَسْمَاءُ الْحُسْنَىٰ فَادْعُوهُ بِهَا',
        translation: 'And to Allah belong the best names, so invoke Him by them',
      },
    ],
    level: 'advanced',
    frequency: 8,
    tags: ['divine attributes', 'theology'],
    collections: ['faith'],
  },
  {
    id: '116',
    arabic: 'صِفَات',
    transliteration: 'ṣifāt',
    meaning: 'Attributes, qualities',
    root: 'و ص ف',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 6,
        ayah: 139,
        arabicText: 'وَقَالُوا مَا فِي بُطُونِ هَٰذِهِ الْأَنْعَامِ خَالِصَةٌ لِّذُكُورِنَا',
        translation: 'And they say, "What is in the wombs of these animals is exclusively for our males"',
      },
    ],
    level: 'advanced',
    frequency: 15,
    tags: ['attributes', 'qualities'],
    collections: ['faith'],
  },
  {
    id: '117',
    arabic: 'بَرْزَخ',
    transliteration: 'barzakh',
    meaning: 'Barrier, intermediate realm',
    root: 'ب ر ز',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 23,
        ayah: 100,
        arabicText: 'وَمِن وَرَائِهِم بَرْزَخٌ إِلَىٰ يَوْمِ يُبْعَثُونَ',
        translation: 'And behind them is a barrier until the Day they are resurrected',
      },
    ],
    level: 'advanced',
    frequency: 3,
    tags: ['afterlife', 'intermediate state'],
    collections: ['afterlife'],
  },
  {
    id: '118',
    arabic: 'كَرَامَة',
    transliteration: 'karāmah',
    meaning: 'Miracle, honor',
    root: 'ك ر م',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 17,
        ayah: 70,
        arabicText: 'وَلَقَدْ كَرَّمْنَا بَنِي آدَمَ وَحَمَلْنَاهُمْ فِي الْبَرِّ وَالْبَحْرِ',
        translation: 'And We have certainly honored the children of Adam and carried them on the land and sea',
      },
    ],
    level: 'advanced',
    frequency: 13,
    tags: ['honor', 'miracle'],
    collections: ['faith'],
  },
  {
    id: '119',
    arabic: 'مُعْجِزَة',
    transliteration: 'mu\'jizah',
    meaning: 'Miracle',
    root: 'ع ج ز',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 17,
        ayah: 88,
        arabicText: 'قُل لَّئِنِ اجْتَمَعَتِ الْإِنسُ وَالْجِنُّ عَلَىٰ أَن يَأْتُوا بِمِثْلِ هَٰذَا الْقُرْآنِ لَا يَأْتُونَ بِمِثْلِهِ',
        translation: 'Say, "If mankind and the jinn gathered in order to produce the like of this Quran, they could not produce the like of it"',
      },
    ],
    level: 'advanced',
    frequency: 22,
    tags: ['miracle', 'proof'],
    collections: ['faith', 'prophets'],
  },
  {
    id: '120',
    arabic: 'وَحْي',
    transliteration: 'waḥy',
    meaning: 'Divine revelation',
    root: 'و ح ي',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 42,
        ayah: 51,
        arabicText: 'وَمَا كَانَ لِبَشَرٍ أَن يُكَلِّمَهُ اللَّهُ إِلَّا وَحْيًا',
        translation: 'And it is not for any human being that Allah should speak to him except by revelation',
      },
    ],
    level: 'advanced',
    frequency: 78,
    tags: ['revelation', 'divine communication'],
    collections: ['faith', 'prophets'],
  },
  {
    id: '121',
    arabic: 'إِلْهَام',
    transliteration: 'ilhām',
    meaning: 'Inspiration',
    root: 'ل ه م',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 91,
        ayah: 8,
        arabicText: 'فَأَلْهَمَهَا فُجُورَهَا وَتَقْوَاهَا',
        translation: 'And inspired it [with discernment of] its wickedness and its righteousness',
      },
    ],
    level: 'advanced',
    frequency: 1,
    tags: ['inspiration', 'divine guidance'],
    collections: ['faith'],
  },
  {
    id: '122',
    arabic: 'فِقْه',
    transliteration: 'fiqh',
    meaning: 'Jurisprudence, understanding',
    root: 'ف ق ه',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 9,
        ayah: 122,
        arabicText: 'وَمَا كَانَ الْمُؤْمِنُونَ لِيَنفِرُوا كَافَّةً ۚ فَلَوْلَا نَفَرَ مِن كُلِّ فِرْقَةٍ مِّنْهُمْ طَائِفَةٌ لِّيَتَفَقَّهُوا فِي الدِّينِ',
        translation: 'And it is not for the believers to go forth [to battle] all at once. For there should separate from every division of them a group [remaining] to obtain understanding in the religion',
      },
    ],
    level: 'advanced',
    frequency: 20,
    tags: ['jurisprudence', 'understanding'],
    collections: ['knowledge'],
  },
  {
    id: '123',
    arabic: 'اجْتِهَاد',
    transliteration: 'ijtihād',
    meaning: 'Independent reasoning in Islamic law',
    root: 'ج ه د',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 29,
        ayah: 6,
        arabicText: 'وَمَن جَاهَدَ فَإِنَّمَا يُجَاهِدُ لِنَفْسِهِ ۚ إِنَّ اللَّهَ لَغَنِيٌّ عَنِ الْعَالَمِينَ',
        translation: 'And whoever strives only strives for [the benefit of] himself. Indeed, Allah is free from need of the worlds',
      },
    ],
    level: 'advanced',
    frequency: 41,
    tags: ['jurisprudence', 'reasoning'],
    collections: ['knowledge'],
  },
  {
    id: '124',
    arabic: 'إِجْمَاع',
    transliteration: 'ijmā\'',
    meaning: 'Consensus',
    root: 'ج م ع',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 8,
        ayah: 46,
        arabicText: 'وَأَطِيعُوا اللَّهَ وَرَسُولَهُ وَلَا تَنَازَعُوا فَتَفْشَلُوا وَتَذْهَبَ رِيحُكُمْ',
        translation: 'And obey Allah and His Messenger, and do not dispute and [thus] lose courage and [then] your strength would depart',
      },
    ],
    level: 'advanced',
    frequency: 127,
    tags: ['consensus', 'unity'],
    collections: ['community'],
  },
  {
    id: '125',
    arabic: 'قِيَاس',
    transliteration: 'qiyās',
    meaning: 'Analogical reasoning',
    root: 'ق ي س',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 59,
        ayah: 18,
        arabicText: 'يَا أَيُّهَا الَّذِينَ آمَنُوا اتَّقُوا اللَّهَ وَلْتَنظُرْ نَفْسٌ مَّا قَدَّمَتْ لِغَدٍ',
        translation: 'O you who have believed, fear Allah. And let every soul look to what it has put forth for tomorrow',
      },
    ],
    level: 'advanced',
    frequency: 3,
    tags: ['reasoning', 'comparison'],
    collections: ['knowledge'],
  },
  {
    id: '126',
    arabic: 'تَفْسِير',
    transliteration: 'tafsīr',
    meaning: 'Exegesis, interpretation',
    root: 'ف س ر',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 25,
        ayah: 33,
        arabicText: 'وَلَا يَأْتُونَكَ بِمَثَلٍ إِلَّا جِئْنَاكَ بِالْحَقِّ وَأَحْسَنَ تَفْسِيرًا',
        translation: 'And they do not come to you with an argument except that We bring you the truth and the best explanation',
      },
    ],
    level: 'advanced',
    frequency: 1,
    tags: ['interpretation', 'explanation'],
    collections: ['knowledge'],
  },
  {
    id: '127',
    arabic: 'تَرْتِيل',
    transliteration: 'tartīl',
    meaning: 'Recitation in measured tones',
    root: 'ر ت ل',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 73,
        ayah: 4,
        arabicText: 'وَرَتِّلِ الْقُرْآنَ تَرْتِيلًا',
        translation: 'And recite the Quran with measured recitation',
      },
    ],
    level: 'advanced',
    frequency: 1,
    tags: ['recitation', 'worship'],
    collections: ['worship'],
  },
  {
    id: '128',
    arabic: 'تَجْوِيد',
    transliteration: 'tajwīd',
    meaning: 'Proper pronunciation and recitation',
    root: 'ج و د',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 73,
        ayah: 4,
        arabicText: 'وَرَتِّلِ الْقُرْآنَ تَرْتِيلًا',
        translation: 'And recite the Quran with measured recitation',
      },
    ],
    level: 'advanced',
    frequency: 0,
    tags: ['recitation', 'pronunciation'],
    collections: ['worship'],
  },
  {
    id: '129',
    arabic: 'خُشُوع',
    transliteration: 'khushū\'',
    meaning: 'Humility, reverence in worship',
    root: 'خ ش ع',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 23,
        ayah: 2,
        arabicText: 'الَّذِينَ هُمْ فِي صَلَاتِهِمْ خَاشِعُونَ',
        translation: 'They who are during their prayer humbly submissive',
      },
    ],
    level: 'advanced',
    frequency: 15,
    tags: ['humility', 'worship'],
    collections: ['worship'],
  },
  {
    id: '130',
    arabic: 'خُضُوع',
    transliteration: 'khuḍū\'',
    meaning: 'Submission, yielding',
    root: 'خ ض ع',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 33,
        ayah: 32,
        arabicText: 'فَلَا تَخْضَعْنَ بِالْقَوْلِ فَيَطْمَعَ الَّذِي فِي قَلْبِهِ مَرَضٌ',
        translation: 'Then do not be soft in speech [to men], lest he in whose heart is disease should covet',
      },
    ],
    level: 'advanced',
    frequency: 4,
    tags: ['submission', 'yielding'],
    collections: ['worship'],
  },
  {
    id: '131',
    arabic: 'تَسْلِيم',
    transliteration: 'taslīm',
    meaning: 'Surrender, submission',
    root: 'س ل م',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 4,
        ayah: 65,
        arabicText: 'فَلَا وَرَبِّكَ لَا يُؤْمِنُونَ حَتَّىٰ يُحَكِّمُوكَ فِيمَا شَجَرَ بَيْنَهُمْ ثُمَّ لَا يَجِدُوا فِي أَنفُسِهِمْ حَرَجًا مِّمَّا قَضَيْتَ وَيُسَلِّمُوا تَسْلِيمًا',
        translation: 'But no, by your Lord, they will not [truly] believe until they make you judge concerning that over which they dispute among themselves and then find within themselves no discomfort from what you have judged and submit in [full, willing] submission',
      },
    ],
    level: 'advanced',
    frequency: 1,
    tags: ['surrender', 'submission'],
    collections: ['faith'],
  },
  {
    id: '132',
    arabic: 'تَعْظِيم',
    transliteration: 'ta\'ẓīm',
    meaning: 'Magnification, glorification',
    root: 'ع ظ م',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 74,
        ayah: 3,
        arabicText: 'وَرَبَّكَ فَكَبِّرْ',
        translation: 'And your Lord glorify',
      },
    ],
    level: 'advanced',
    frequency: 23,
    tags: ['glorification', 'magnification'],
    collections: ['worship'],
  },
  {
    id: '133',
    arabic: 'تَكْبِير',
    transliteration: 'takbīr',
    meaning: 'Saying "Allahu Akbar"',
    root: 'ك ب ر',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 74,
        ayah: 3,
        arabicText: 'وَرَبَّكَ فَكَبِّرْ',
        translation: 'And your Lord glorify',
      },
    ],
    level: 'advanced',
    frequency: 35,
    tags: ['glorification', 'worship'],
    collections: ['worship'],
  },
  {
    id: '134',
    arabic: 'تَهْلِيل',
    transliteration: 'tahlīl',
    meaning: 'Saying "La ilaha illa Allah"',
    root: 'ه ل ل',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 37,
        ayah: 35,
        arabicText: 'إِنَّهُمْ كَانُوا إِذَا قِيلَ لَهُمْ لَا إِلَٰهَ إِلَّا اللَّهُ يَسْتَكْبِرُونَ',
        translation: 'Indeed they, when it was said to them, "There is no deity but Allah," were arrogant',
      },
    ],
    level: 'advanced',
    frequency: 2,
    tags: ['declaration of faith', 'worship'],
    collections: ['worship'],
  },
  {
    id: '135',
    arabic: 'اسْتِقَامَة',
    transliteration: 'istiqāmah',
    meaning: 'Steadfastness, uprightness',
    root: 'ق و م',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 11,
        ayah: 112,
        arabicText: 'فَاسْتَقِمْ كَمَا أُمِرْتَ وَمَن تَابَ مَعَكَ وَلَا تَطْغَوْا',
        translation: 'So remain on a right course as you have been commanded, [you] and those who have turned back with you [to Allah], and do not transgress',
      },
    ],
    level: 'advanced',
    frequency: 17,
    tags: ['steadfastness', 'righteousness'],
    collections: ['ethics'],
  },
  {
    id: '136',
    arabic: 'ثَبَات',
    transliteration: 'thabāt',
    meaning: 'Firmness, stability',
    root: 'ث ب ت',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 14,
        ayah: 27,
        arabicText: 'يُثَبِّتُ اللَّهُ الَّذِينَ آمَنُوا بِالْقَوْلِ الثَّابِتِ فِي الْحَيَاةِ الدُّنْيَا وَفِي الْآخِرَةِ',
        translation: 'Allah keeps firm those who believe, with the firm word, in worldly life and in the Hereafter',
      },
    ],
    level: 'advanced',
    frequency: 58,
    tags: ['firmness', 'stability'],
    collections: ['faith'],
  },
  {
    id: '137',
    arabic: 'زَوَال',
    transliteration: 'zawāl',
    meaning: 'Decline, disappearance',
    root: 'ز و ل',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 14,
        ayah: 46,
        arabicText: 'وَقَدْ مَكَرُوا مَكْرَهُمْ وَعِندَ اللَّهِ مَكْرُهُمْ وَإِن كَانَ مَكْرُهُمْ لِتَزُولَ مِنْهُ الْجِبَالُ',
        translation: 'And they had planned their plan, but with Allah is their plan, even if their plan had been [sufficient] to do away with the mountains',
      },
    ],
    level: 'advanced',
    frequency: 5,
    tags: ['decline', 'disappearance'],
    collections: ['nature'],
  },
  {
    id: '138',
    arabic: 'بَقَاء',
    transliteration: 'baqā\'',
    meaning: 'Permanence, survival',
    root: 'ب ق ي',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 55,
        ayah: 27,
        arabicText: 'وَيَبْقَىٰ وَجْهُ رَبِّكَ ذُو الْجَلَالِ وَالْإِكْرَامِ',
        translation: 'And there will remain the Face of your Lord, Owner of Majesty and Honor',
      },
    ],
    level: 'advanced',
    frequency: 83,
    tags: ['permanence', 'survival'],
    collections: ['faith'],
  },
  {
    id: '139',
    arabic: 'خُلُود',
    transliteration: 'khulūd',
    meaning: 'Eternity, immortality',
    root: 'خ ل د',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 25,
        arabicText: 'وَبَشِّرِ الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ أَنَّ لَهُمْ جَنَّاتٍ تَجْرِي مِن تَحْتِهَا الْأَنْهَارُ ۖ كُلَّمَا رُزِقُوا مِنْهَا مِن ثَمَرَةٍ رِّزْقًا ۙ قَالُوا هَٰذَا الَّذِي رُزِقْنَا مِن قَبْلُ ۖ وَأُتُوا بِهِ مُتَشَابِهًا ۖ وَلَهُمْ فِيهَا أَزْوَاجٌ مُّطَهَّرَةٌ ۖ وَهُمْ فِيهَا خَالِدُونَ',
        translation: 'And give good tidings to those who believe and do righteous deeds that they will have gardens beneath which rivers flow. Whenever they are provided with a provision of fruit therefrom, they will say, "This is what we were provided with before." And it is given to them in likeness. And they will have therein purified spouses, and they will abide therein eternally',
      },
    ],
    level: 'advanced',
    frequency: 104,
    tags: ['eternity', 'immortality'],
    collections: ['afterlife'],
  },
  {
    id: '140',
    arabic: 'فَنَاء',
    transliteration: 'fanā\'',
    meaning: 'Annihilation, passing away',
    root: 'ف ن ي',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 55,
        ayah: 26,
        arabicText: 'كُلُّ مَنْ عَلَيْهَا فَانٍ',
        translation: 'Everyone upon the earth will perish',
      },
    ],
    level: 'advanced',
    frequency: 3,
    tags: ['annihilation', 'passing away'],
    collections: ['afterlife'],
  },
];
