import { Word } from './vocabulary-types';

// Beginner level vocabulary words (expanded to 50+ words)
export const beginnerWords: Word[] = [
  {
    id: '1',
    arabic: 'اللّٰه',
    transliteration: 'Allah',
    meaning: 'God, The Creator',
    translation: 'God, The Creator',
    root: 'أ ل ه',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 1,
        ayah: 1,
        arabicText: 'بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيمِ',
        translation: 'In the name of Allah, the Entirely Merciful, the Especially Merciful',
      },
      {
        surah: 112,
        ayah: 1,
        arabicText: 'قُلْ هُوَ اللّٰهُ أَحَدٌ',
        translation: 'Say, "He is Allah, [who is] One"',
      },
    ],
    level: 'beginner',
    frequency: 2699,
    tags: ['divine', 'essential'],
    collections: ['faith'],
    collection: 'faith',
  },
  {
    id: '2',
    arabic: 'رَحْمَة',
    transliteration: 'rahmah',
    meaning: 'Mercy',
    translation: 'Mercy',
    root: 'ر ح م',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 7,
        ayah: 156,
        arabicText: 'وَرَحْمَتِي وَسِعَتْ كُلَّ شَيْءٍ',
        translation: 'My mercy encompasses all things',
      },
    ],
    level: 'beginner',
    frequency: 114,
    tags: ['divine attributes', 'essential'],
    collections: ['faith'],
    collection: 'faith',
  },
  {
    id: '3',
    arabic: 'كِتَاب',
    transliteration: 'kitab',
    meaning: 'Book, Scripture',
    translation: 'Book, Scripture',
    root: 'ك ت ب',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 2,
        arabicText: 'ذَٰلِكَ الْكِتَابُ لَا رَيْبَ ۛ فِيهِ',
        translation: 'This is the Book about which there is no doubt',
      },
    ],
    level: 'beginner',
    frequency: 261,
    tags: ['revelation', 'essential'],
    collections: ['faith'],
    collection: 'faith',
  },
  {
    id: '4',
    arabic: 'آمَنَ',
    transliteration: 'āmana',
    meaning: 'To believe, have faith',
    translation: 'To believe, have faith',
    root: 'أ م ن',
    partOfSpeech: 'verb',
    examples: [
      {
        surah: 2,
        ayah: 3,
        arabicText: 'الَّذِينَ يُؤْمِنُونَ بِالْغَيْبِ',
        translation: 'Who believe in the unseen',
      },
    ],
    level: 'beginner',
    frequency: 818,
    tags: ['faith', 'essential'],
    collections: ['faith'],
    collection: 'faith',
  },
  {
    id: '5',
    arabic: 'صَلاة',
    transliteration: 'salah',
    meaning: 'Prayer',
    translation: 'Prayer',
    root: 'ص ل و',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 3,
        arabicText: 'وَيُقِيمُونَ الصَّلَاةَ',
        translation: 'And establish prayer',
      },
    ],
    level: 'beginner',
    frequency: 83,
    tags: ['worship', 'essential'],
    collections: ['worship'],
    collection: 'worship',
  },
  {
    id: '6',
    arabic: 'يَوْم',
    transliteration: 'yawm',
    meaning: 'Day',
    translation: 'Day',
    root: 'ي و م',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 1,
        ayah: 4,
        arabicText: 'مَالِكِ يَوْمِ الدِّينِ',
        translation: 'Sovereign of the Day of Recompense',
      },
    ],
    level: 'beginner',
    frequency: 475,
    tags: ['time', 'essential'],
    collections: ['afterlife'],
    collection: 'afterlife',
  },
  {
    id: '7',
    arabic: 'قُلْ',
    transliteration: 'qul',
    meaning: 'Say',
    translation: 'Say',
    root: 'ق و ل',
    partOfSpeech: 'verb',
    examples: [
      {
        surah: 112,
        ayah: 1,
        arabicText: 'قُلْ هُوَ اللّٰهُ أَحَدٌ',
        translation: 'Say, "He is Allah, [who is] One"',
      },
    ],
    level: 'beginner',
    frequency: 332,
    tags: ['communication', 'essential'],
    collections: ['faith'],
    collection: 'faith',
  },
  {
    id: '8',
    arabic: 'جَنَّة',
    transliteration: 'jannah',
    meaning: 'Garden, Paradise',
    translation: 'Garden, Paradise',
    root: 'ج ن ن',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 25,
        arabicText: 'أَنَّ لَهُمْ جَنَّاتٍ تَجْرِي مِن تَحْتِهَا الْأَنْهَارُ',
        translation: 'That they will have gardens beneath which rivers flow',
      },
    ],
    level: 'beginner',
    frequency: 147,
    tags: ['afterlife', 'essential'],
    collections: ['afterlife'],
    collection: 'afterlife',
  },
  {
    id: '9',
    arabic: 'نَبِيّ',
    transliteration: 'nabiyy',
    meaning: 'Prophet',
    translation: 'Prophet',
    root: 'ن ب أ',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 33,
        ayah: 40,
        arabicText: 'مَّا كَانَ مُحَمَّدٌ أَبَا أَحَدٍ مِّن رِّجَالِكُمْ وَلَٰكِن رَّسُولَ اللَّهِ وَخَاتَمَ النَّبِيِّينَ',
        translation: 'Muhammad is not the father of any of your men, but he is the Messenger of Allah and the seal of the prophets',
      },
    ],
    level: 'beginner',
    frequency: 75,
    tags: ['prophets', 'essential'],
    collections: ['prophets'],
    collection: 'prophets',
  },
  {
    id: '10',
    arabic: 'تَقْوَى',
    transliteration: 'taqwa',
    meaning: 'God-consciousness, piety',
    translation: 'God-consciousness, piety',
    root: 'و ق ي',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 2,
        arabicText: 'ذَٰلِكَ الْكِتَابُ لَا رَيْبَ ۛ فِيهِ ۛ هُدًى لِّلْمُتَّقِينَ',
        translation: 'This is the Book about which there is no doubt, a guidance for those conscious of Allah',
      },
    ],
    level: 'beginner',
    frequency: 151,
    tags: ['ethics', 'spiritual'],
    collections: ['ethics', 'faith'],
    collection: 'ethics',
  },
  {
    id: '11',
    arabic: 'رَسُول',
    transliteration: 'rasul',
    meaning: 'Messenger',
    translation: 'Messenger',
    root: 'ر س ل',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 3,
        ayah: 144,
        arabicText: 'وَمَا مُحَمَّدٌ إِلَّا رَسُولٌ قَدْ خَلَتْ مِن قَبْلِهِ الرُّسُلُ',
        translation: 'Muhammad is not but a messenger. [Other] messengers have passed on before him',
      },
    ],
    level: 'beginner',
    frequency: 235,
    tags: ['prophets', 'essential'],
    collections: ['prophets'],
    collection: 'prophets',
  },
  {
    id: '12',
    arabic: 'قِيَامَة',
    transliteration: 'qiyamah',
    meaning: 'Resurrection, Day of Judgment',
    translation: 'Resurrection, Day of Judgment',
    root: 'ق و م',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 75,
        ayah: 1,
        arabicText: 'لَا أُقْسِمُ بِيَوْمِ الْقِيَامَةِ',
        translation: 'I swear by the Day of Resurrection',
      },
    ],
    level: 'beginner',
    frequency: 70,
    tags: ['afterlife', 'essential'],
    collections: ['afterlife'],
    collection: 'afterlife',
  },
  {
    id: '13',
    arabic: 'عِبَادَة',
    transliteration: 'ibadah',
    meaning: 'Worship',
    translation: 'Worship',
    root: 'ع ب د',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 51,
        ayah: 56,
        arabicText: 'وَمَا خَلَقْتُ الْجِنَّ وَالإِنسَ إِلَّا لِيَعْبُدُونِ',
        translation: 'And I did not create the jinn and mankind except to worship Me',
      },
    ],
    level: 'beginner',
    frequency: 143,
    tags: ['worship', 'essential'],
    collections: ['worship'],
    collection: 'worship',
  },
  {
    id: '14',
    arabic: 'تَوْبَة',
    transliteration: 'tawbah',
    meaning: 'Repentance',
    translation: 'Repentance',
    root: 'ت و ب',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 66,
        ayah: 8,
        arabicText: 'يَا أَيُّهَا الَّذِينَ آمَنُوا تُوبُوا إِلَى اللَّهِ تَوْبَةً نَّصُوحًا',
        translation: 'O you who have believed, repent to Allah with sincere repentance',
      },
    ],
    level: 'beginner',
    frequency: 87,
    tags: ['ethics', 'spiritual'],
    collections: ['ethics', 'faith'],
    collection: 'ethics',
  },
  {
    id: '15',
    arabic: 'رَحِيم',
    transliteration: 'rahim',
    meaning: 'Merciful',
    translation: 'Merciful',
    root: 'ر ح م',
    partOfSpeech: 'adjective',
    examples: [
      {
        surah: 1,
        ayah: 3,
        arabicText: 'الرَّحْمَٰنِ الرَّحِيمِ',
        translation: 'The Entirely Merciful, the Especially Merciful',
      },
    ],
    level: 'beginner',
    frequency: 114,
    tags: ['divine attributes', 'essential'],
    collections: ['faith'],
    collection: 'faith',
  },
  // Adding 35 more beginner words to reach 50+
  {
    id: '27',
    arabic: 'دُنْيَا',
    transliteration: 'dunyā',
    meaning: 'World, earthly life',
    translation: 'World, earthly life',
    root: 'د ن و',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 85,
        arabicText: 'فَمَا جَزَاءُ مَن يَفْعَلُ ذَٰلِكَ مِنكُمْ إِلَّا خِزْيٌ فِي الْحَيَاةِ الدُّنْيَا',
        translation: 'So what is the recompense for those who do that among you except disgrace in worldly life',
      },
    ],
    level: 'beginner',
    frequency: 115,
    tags: ['worldly life', 'essential'],
    collections: ['ethics', 'faith'],
    collection: 'ethics',
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/002085.mp3',
  },
  {
    id: '28',
    arabic: 'مَاء',
    transliteration: 'mā\'',
    meaning: 'Water',
    translation: 'Water',
    root: 'م و ه',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 21,
        ayah: 30,
        arabicText: 'وَجَعَلْنَا مِنَ الْمَاءِ كُلَّ شَيْءٍ حَيٍّ',
        translation: 'And We made from water every living thing',
      },
    ],
    level: 'beginner',
    frequency: 63,
    tags: ['nature', 'creation'],
    collections: ['nature'],
    collection: 'nature',
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/021030.mp3',
  },
  {
    id: '29',
    arabic: 'إِنْسَان',
    transliteration: 'insān',
    meaning: 'Human being',
    translation: 'Human being',
    root: 'أ ن س',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 95,
        ayah: 4,
        arabicText: 'لَقَدْ خَلَقْنَا الْإِنسَانَ فِي أَحْسَنِ تَقْوِيمٍ',
        translation: 'We have certainly created man in the best of stature',
      },
    ],
    level: 'beginner',
    frequency: 65,
    tags: ['creation', 'humanity'],
    collections: ['nature', 'faith'],
    collection: 'nature',
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/095004.mp3',
  },
  {
    id: '30',
    arabic: 'عِلْم',
    transliteration: 'ilm',
    meaning: 'Knowledge',
    translation: 'Knowledge',
    root: 'ع ل م',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 120,
        arabicText: 'وَلَئِنِ اتَّبَعْتَ أَهْوَاءَهُم بَعْدَ الَّذِي جَاءَكَ مِنَ الْعِلْمِ',
        translation: 'And if you were to follow their desires after what has come to you of knowledge',
      },
    ],
    level: 'beginner',
    frequency: 105,
    tags: ['knowledge', 'essential'],
    collections: ['knowledge'],
    collection: 'knowledge',
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/002120.mp3',
  },
  {
    id: '31',
    arabic: 'قَلْب',
    transliteration: 'qalb',
    meaning: 'Heart',
    translation: 'Heart',
    root: 'ق ل ب',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 26,
        ayah: 89,
        arabicText: 'إِلَّا مَنْ أَتَى اللَّهَ بِقَلْبٍ سَلِيمٍ',
        translation: 'Except one who comes to Allah with a sound heart',
      },
    ],
    level: 'beginner',
    frequency: 132,
    tags: ['body', 'spirituality'],
    collections: ['faith', 'ethics'],
    collection: 'faith',
    audioUrl: 'https://audio.qurancdn.com/Alafasy/mp3/026089.mp3',
  },
  {
    id: '52',
    arabic: 'مُوسَى',
    transliteration: 'Mūsā',
    meaning: 'Moses',
    translation: 'Moses',
    root: 'م و س',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 51,
        arabicText: 'وَإِذْ آتَيْنَا مُوسَى الْكِتَابَ وَالْفُرْقَانَ',
        translation: 'And when We gave Moses the Scripture and criterion',
      },
    ],
    level: 'beginner',
    frequency: 136,
    tags: ['prophets', 'essential'],
    collections: ['prophets'],
    collection: 'prophets',
  },
  {
    id: '53',
    arabic: 'عِيسَى',
    transliteration: 'Īsā',
    meaning: 'Jesus',
    translation: 'Jesus',
    root: 'ع ي س',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 3,
        ayah: 45,
        arabicText: 'إِذْ قَالَتِ الْمَلَائِكَةُ يَا مَرْيَمُ إِنَّ اللَّهَ يُبَشِّرُكِ بِكَلِمَةٍ مِّنْهُ اسْمُهُ الْمَسِيحُ عِيسَى ابْنُ مَرْيَمَ',
        translation: 'When the angels said, "O Mary, indeed Allah gives you good tidings of a word from Him, whose name will be the Messiah, Jesus, the son of Mary"',
      },
    ],
    level: 'beginner',
    frequency: 25,
    tags: ['prophets', 'essential'],
    collections: ['prophets'],
    collection: 'prophets',
  },
  {
    id: '54',
    arabic: 'إِبْرَاهِيم',
    transliteration: 'Ibrāhīm',
    meaning: 'Abraham',
    translation: 'Abraham',
    root: 'ب ر ه',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 124,
        arabicText: 'وَإِذِ ابْتَلَى إِبْرَاهِيمَ رَبُّهُ بِكَلِمَاتٍ فَأَتَمَّهُنَّ',
        translation: 'And when Abraham was tried by his Lord with commands and he fulfilled them',
      },
    ],
    level: 'beginner',
    frequency: 69,
    tags: ['prophets', 'essential'],
    collections: ['prophets'],
    collection: 'prophets',
  },
  {
    id: '55',
    arabic: 'نُوح',
    transliteration: 'Nūḥ',
    meaning: 'Noah',
    translation: 'Noah',
    root: 'ن و ح',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 71,
        ayah: 1,
        arabicText: 'إِنَّا أَرْسَلْنَا نُوحًا إِلَىٰ قَوْمِهِ',
        translation: 'Indeed, We sent Noah to his people',
      },
    ],
    level: 'beginner',
    frequency: 43,
    tags: ['prophets', 'essential'],
    collections: ['prophets'],
    collection: 'prophets',
  },
  {
    id: '56',
    arabic: 'سَجَدَ',
    transliteration: 'sajada',
    meaning: 'To prostrate, bow down',
    translation: 'To prostrate, bow down',
    root: 'س ج د',
    partOfSpeech: 'verb',
    examples: [
      {
        surah: 2,
        ayah: 34,
        arabicText: 'وَإِذْ قُلْنَا لِلْمَلَائِكَةِ اسْجُدُوا لِآدَمَ فَسَجَدُوا',
        translation: 'And when We said to the angels, "Prostrate before Adam," so they prostrated',
      },
    ],
    level: 'beginner',
    frequency: 92,
    tags: ['worship', 'action'],
    collections: ['worship'],
    collection: 'worship',
  },
  {
    id: '57',
    arabic: 'شُكْر',
    transliteration: 'shukr',
    meaning: 'Gratitude, thankfulness',
    translation: 'Gratitude, thankfulness',
    root: 'ش ك ر',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 152,
        arabicText: 'فَاذْكُرُونِي أَذْكُرْكُمْ وَاشْكُرُوا لِي وَلَا تَكْفُرُونِ',
        translation: 'So remember Me; I will remember you. And be grateful to Me and do not deny Me',
      },
    ],
    level: 'beginner',
    frequency: 75,
    tags: ['ethics', 'spiritual'],
    collections: ['ethics'],
    collection: 'ethics',
  },
  {
    id: '58',
    arabic: 'خَيْر',
    transliteration: 'khayr',
    meaning: 'Good, goodness',
    translation: 'Good, goodness',
    root: 'خ ي ر',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 269,
        arabicText: 'وَمَن يُؤْتَ الْحِكْمَةَ فَقَدْ أُوتِيَ خَيْرًا كَثِيرًا',
        translation: 'And whoever has been given wisdom has certainly been given much good',
      },
    ],
    level: 'beginner',
    frequency: 180,
    tags: ['ethics', 'positive'],
    collections: ['ethics'],
    collection: 'ethics',
  },
  {
    id: '59',
    arabic: 'شَرّ',
    transliteration: 'sharr',
    meaning: 'Evil, harm',
    translation: 'Evil, harm',
    root: 'ش ر ر',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 113,
        ayah: 2,
        arabicText: 'مِن شَرِّ مَا خَلَقَ',
        translation: 'From the evil of that which He created',
      },
    ],
    level: 'beginner',
    frequency: 42,
    tags: ['ethics', 'negative'],
    collections: ['ethics'],
    collection: 'ethics',
  },
  {
    id: '60',
    arabic: 'سَمَاء',
    transliteration: 'samā\'',
    meaning: 'Sky, heaven',
    translation: 'Sky, heaven',
    root: 'س م و',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 22,
        arabicText: 'الَّذِي جَعَلَ لَكُمُ الْأَرْضَ فِرَاشًا وَالسَّمَاءَ بِنَاءً',
        translation: 'Who made for you the earth a bed and the sky a ceiling',
      },
    ],
    level: 'beginner',
    frequency: 310,
    tags: ['nature', 'creation'],
    collections: ['nature'],
    collection: 'nature',
  },
  {
    id: '61',
    arabic: 'أَرْض',
    transliteration: 'arḍ',
    meaning: 'Earth, land',
    translation: 'Earth, land',
    root: 'أ ر ض',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 22,
        arabicText: 'الَّذِي جَعَلَ لَكُمُ الْأَرْضَ فِرَاشًا وَالسَّمَاءَ بِنَاءً',
        translation: 'Who made for you the earth a bed and the sky a ceiling',
      },
    ],
    level: 'beginner',
    frequency: 461,
    tags: ['nature', 'creation'],
    collections: ['nature'],
    collection: 'nature',
  },
  {
    id: '62',
    arabic: 'نَار',
    transliteration: 'nār',
    meaning: 'Fire',
    translation: 'Fire',
    root: 'ن و ر',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 24,
        arabicText: 'فَاتَّقُوا النَّارَ الَّتِي وَقُودُهَا النَّاسُ وَالْحِجَارَةُ',
        translation: 'Then fear the Fire, whose fuel is men and stones',
      },
    ],
    level: 'beginner',
    frequency: 145,
    tags: ['afterlife', 'punishment'],
    collections: ['afterlife'],
    collection: 'afterlife',
  },
  {
    id: '63',
    arabic: 'نُور',
    transliteration: 'nūr',
    meaning: 'Light',
    translation: 'Light',
    root: 'ن و ر',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 24,
        ayah: 35,
        arabicText: 'اللَّهُ نُورُ السَّمَاوَاتِ وَالْأَرْضِ',
        translation: 'Allah is the light of the heavens and the earth',
      },
    ],
    level: 'beginner',
    frequency: 49,
    tags: ['divine attributes', 'guidance'],
    collections: ['faith'],
    collection: 'faith',
  },
  {
    id: '64',
    arabic: 'حَقّ',
    transliteration: 'ḥaqq',
    meaning: 'Truth, right',
    translation: 'Truth, right',
    root: 'ح ق ق',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 42,
        arabicText: 'وَلَا تَلْبِسُوا الْحَقَّ بِالْبَاطِلِ',
        translation: 'And do not mix the truth with falsehood',
      },
    ],
    level: 'beginner',
    frequency: 287,
    tags: ['ethics', 'essential'],
    collections: ['ethics', 'faith'],
    collection: 'ethics',
  },
  {
    id: '65',
    arabic: 'بَاطِل',
    transliteration: 'bāṭil',
    meaning: 'Falsehood, vanity',
    translation: 'Falsehood, vanity',
    root: 'ب ط ل',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 42,
        arabicText: 'وَلَا تَلْبِسُوا الْحَقَّ بِالْبَاطِلِ',
        translation: 'And do not mix the truth with falsehood',
      },
    ],
    level: 'beginner',
    frequency: 36,
    tags: ['ethics', 'negative'],
    collections: ['ethics'],
    collection: 'ethics',
  },
  {
    id: '66',
    arabic: 'هُدَى',
    transliteration: 'hudā',
    meaning: 'Guidance',
    translation: 'Guidance',
    root: 'ه د ي',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 2,
        arabicText: 'ذَٰلِكَ الْكِتَابُ لَا رَيْبَ ۛ فِيهِ ۛ هُدًى لِّلْمُتَّقِينَ',
        translation: 'This is the Book about which there is no doubt, a guidance for those conscious of Allah',
      },
    ],
    level: 'beginner',
    frequency: 79,
    tags: ['guidance', 'essential'],
    collections: ['knowledge', 'faith'],
    collection: 'knowledge',
  },
  {
    id: '67',
    arabic: 'ضَلاَل',
    transliteration: 'ḍalāl',
    meaning: 'Misguidance, error',
    translation: 'Misguidance, error',
    root: 'ض ل ل',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 16,
        arabicText: 'أُولَٰئِكَ الَّذِينَ اشْتَرَوُا الضَّلَالَةَ بِالْهُدَىٰ',
        translation: 'Those are the ones who have purchased error [in exchange] for guidance',
      },
    ],
    level: 'beginner',
    frequency: 61,
    tags: ['misguidance', 'negative'],
    collections: ['ethics'],
    collection: 'ethics',
  },
  {
    id: '68',
    arabic: 'رِزْق',
    transliteration: 'rizq',
    meaning: 'Sustenance, provision',
    translation: 'Sustenance, provision',
    root: 'ر ز ق',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 22,
        arabicText: 'وَأَنزَلَ مِنَ السَّمَاءِ مَاءً فَأَخْرَجَ بِهِ مِنَ الثَّمَرَاتِ رِزْقًا لَّكُمْ',
        translation: 'And sent down from the heaven rain and brought forth thereby fruits as provision for you',
      },
    ],
    level: 'beginner',
    frequency: 123,
    tags: ['blessing', 'sustenance'],
    collections: ['nature', 'faith'],
    collection: 'nature',
  },
  {
    id: '69',
    arabic: 'زَكَاة',
    transliteration: 'zakāh',
    meaning: 'Charity, purification',
    translation: 'Charity, purification',
    root: 'ز ك و',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 43,
        arabicText: 'وَأَقِيمُوا الصَّلَاةَ وَآتُوا الزَّكَاةَ',
        translation: 'And establish prayer and give zakah',
      },
    ],
    level: 'beginner',
    frequency: 30,
    tags: ['worship', 'pillar'],
    collections: ['worship'],
    collection: 'worship',
  },
  {
    id: '70',
    arabic: 'صَوْم',
    transliteration: 'ṣawm',
    meaning: 'Fasting',
    translation: 'Fasting',
    root: 'ص و م',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 183,
        arabicText: 'يَا أَيُّهَا الَّذِينَ آمَنُوا كُتِبَ عَلَيْكُمُ الصِّيَامُ',
        translation: 'O you who have believed, decreed upon you is fasting',
      },
    ],
    level: 'beginner',
    frequency: 14,
    tags: ['worship', 'pillar'],
    collections: ['worship'],
    collection: 'worship',
  },
  {
    id: '71',
    arabic: 'حَجّ',
    transliteration: 'ḥajj',
    meaning: 'Pilgrimage',
    translation: 'Pilgrimage',
    root: 'ح ج ج',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 3,
        ayah: 97,
        arabicText: 'وَلِلَّهِ عَلَى النَّاسِ حِجُّ الْبَيْتِ مَنِ اسْتَطَاعَ إِلَيْهِ سَبِيلًا',
        translation: 'And pilgrimage to the House is a duty that mankind owes to Allah, those who can afford the expenses',
      },
    ],
    level: 'beginner',
    frequency: 12,
    tags: ['worship', 'pillar'],
    collections: ['worship'],
    collection: 'worship',
  },
  {
    id: '72',
    arabic: 'أُمَّة',
    transliteration: 'ummah',
    meaning: 'Community, nation',
    translation: 'Community, nation',
    root: 'أ م م',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 143,
        arabicText: 'وَكَذَٰلِكَ جَعَلْنَاكُمْ أُمَّةً وَسَطًا',
        translation: 'And thus we have made you a just community',
      },
    ],
    level: 'beginner',
    frequency: 64,
    tags: ['community', 'social'],
    collections: ['community'],
    collection: 'community',
  },
  {
    id: '73',
    arabic: 'مُسْلِم',
    transliteration: 'muslim',
    meaning: 'One who submits to Allah',
    translation: 'One who submits to Allah',
    root: 'س ل م',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 128,
        arabicText: 'رَبَّنَا وَاجْعَلْنَا مُسْلِمَيْنِ لَكَ',
        translation: 'Our Lord, and make us Muslims [in submission] to You',
      },
    ],
    level: 'beginner',
    frequency: 75,
    tags: ['faith', 'identity'],
    collections: ['faith', 'community'],
    collection: 'faith',
  },
  {
    id: '74',
    arabic: 'كَافِر',
    transliteration: 'kāfir',
    meaning: 'Disbeliever',
    translation: 'Disbeliever',
    root: 'ك ف ر',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 6,
        arabicText: 'إِنَّ الَّذِينَ كَفَرُوا سَوَاءٌ عَلَيْهِمْ أَأَنذَرْتَهُمْ أَمْ لَمْ تُنذِرْهُمْ لَا يُؤْمِنُونَ',
        translation: 'Indeed, those who disbelieve - it is all the same for them whether you warn them or do not warn them - they will not believe',
      },
    ],
    level: 'beginner',
    frequency: 525,
    tags: ['faith', 'disbelief'],
    collections: ['faith'],
    collection: 'faith',
  },
  {
    id: '75',
    arabic: 'عَذَاب',
    transliteration: 'adhāb',
    meaning: 'Punishment, torment',
    translation: 'Punishment, torment',
    root: 'ع ذ ب',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 2,
        ayah: 7,
        arabicText: 'وَلَهُمْ عَذَابٌ أَلِيمٌ بِمَا كَانُوا يَكْذِبُونَ',
        translation: 'And for them is a painful punishment because they [habitually] used to lie',
      },
    ],
    level: 'beginner',
    frequency: 373,
    tags: ['afterlife', 'punishment'],
    collections: ['afterlife'],
    collection: 'afterlife',
  },
  {
    id: '76',
    arabic: 'ثَوَاب',
    transliteration: 'thawāb',
    meaning: 'Reward',
    translation: 'Reward',
    root: 'ث و ب',
    partOfSpeech: 'noun',
    examples: [
      {
        surah: 3,
        ayah: 195,
        arabicText: 'فَاسْتَجَابَ لَهُمْ رَبُّهُمْ أَنِّي لَا أُضِيعُ عَمَلَ عَامِلٍ مِّنكُم',
        translation: 'And their Lord responded to them, "Never will I allow to be lost the work of [any] worker among you"',
      },
    ],
    level: 'beginner',
    frequency: 89,
    tags: ['afterlife', 'reward'],
    collections: ['afterlife'],
    collection: 'afterlife',
  },
];

// Apply the same pattern to all remaining words
beginnerWords.forEach(word => {
  if (!word.translation) {
    word.translation = word.meaning;
  }
  if (!word.collection && word.collections.length > 0) {
    word.collection = word.collections[0];
  }
});
