// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozacrpxnfywmueasbhbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96YWNycHhuZnl3bXVlYXNiaGJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1OTM3MjEsImV4cCI6MjA1NjE2OTcyMX0._xof3RVQq7Nhm_gm90WUIFnxVIT2nRjUiwyFWh2JJic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);